In [2]:
import numpy as np
from numpy import random
import pandas as pd

myarray = np.arange(0,1000,1)
print("Myarray: \n", myarray)

zeroarray = np.zeros((1000,1000))
print("\nZeroarray: \n", zeroarray)

onearray = np.ones((1000,1000))
print("\nOnearray: \n", onearray)

Myarray: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243

In [3]:
0*0

0

In [4]:
1*0

0

In [5]:
1*1

1

In [6]:
0**0

1

In [7]:
1**0

1

In [8]:
10**0.5

3.1622776601683795

In [9]:
1**0.5

1.0

In [10]:
0.1**0.5

0.31622776601683794

In [25]:
import math
math.exp(1)

2.718281828459045

Therefore, I can use matrix mutiplication to do an array of booleans very quickly if I can find out how to generate a 1 or 0 for each feature? Or perhaps I can use an alternative means of ensuring the output number is clearly distinguishable in some manner from other features.

In [11]:
a = np.array([[1, 0],
              [2, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[ 4,  1],
       [10,  4]])

Example random matrix of numbers to do true false check

In [12]:
from numpy.random import default_rng
rand_array = default_rng(42).random((1000,1000))
rand_array[0,1] = 0
rand_array[0,0] = 1
print(rand_array)

[[1.         0.         0.85859792 ... 0.00230877 0.9933685  0.28089639]
 [0.06206311 0.45826204 0.12903006 ... 0.33504688 0.8456994  0.52007191]
 [0.84273197 0.44638949 0.95297516 ... 0.21008712 0.97924324 0.09807983]
 ...
 [0.155427   0.50875261 0.54351498 ... 0.03334632 0.2737543  0.82154411]
 [0.10032557 0.94148934 0.53453367 ... 0.69086517 0.49008486 0.69983763]
 [0.52578891 0.77158303 0.84801206 ... 0.55082789 0.98694171 0.66717687]]


Multiplication doesn't work:

In [13]:
print(np.matmul(rand_array, zeroarray))
print(rand_array@onearray)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[496.96500404 496.96500404 496.96500404 ... 496.96500404 496.96500404
  496.96500404]
 [508.49559857 508.49559857 508.49559857 ... 508.49559857 508.49559857
  508.49559857]
 [492.8734465  492.8734465  492.8734465  ... 492.8734465  492.8734465
  492.8734465 ]
 ...
 [516.31154455 516.31154455 516.31154455 ... 516.31154455 516.31154455
  516.31154455]
 [505.65816935 505.65816935 505.65816935 ... 505.65816935 505.65816935
  505.65816935]
 [501.07104011 501.07104011 501.07104011 ... 501.07104011 501.07104011
  501.07104011]]


But a comparison for boolean does from stackoverflow:

In [14]:
x = np.array([[1,0,1],[0,0,1],[1,1,0]])
y = np.array([[1,0,1],[0,0,1],[1,1,1]])
print((x == y).sum() / x.size) #a number between 0 and 1 of similarity of two matrices in terms of number of elements on a axis
print(x == y)

0.8888888888888888
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]


Comparison of matrix to matrix comparison, einsum calculation and direct comparison boolean to a boolean rule.
Maybe investigate a simplification of calculation by applying a kernel function to matrix through K maps if doing several calc steps to a matrix?: https://en.wikipedia.org/wiki/Karnaugh_map

In [15]:
import time
import tensorflow as tf
start = time.time()
print(rand_array.size)
print((rand_array == onearray).sum() / rand_array.size)
print(rand_array == onearray)
finish = time.time() - start
print("Time in seconds (compare an array == another array): \n", finish)

newstart = time.time()
e = tf.einsum('ij,jk->ik', rand_array, onearray)
print(e)
newfinish = time.time() - newstart
print("Newtime in seconds (tf.einsum): \n",newfinish)

newnewstart = time.time()
print((rand_array < 0.5).sum() / rand_array.size)
print(rand_array < 0.5)
newnewfinish = time.time() - newnewstart
print("Newnewtime in seconds(array scalars less than a value): \n",newnewfinish)

newnewstart2 = time.time()
bool_array = (rand_array < 0.5)
print(np.where(bool_array, rand_array, 0))
newnewfinish2 = time.time() - newnewstart2
print("Newnewtime2 in seconds (array scalars less than a value, then show only under a value condition): \n",newnewfinish2)

newnewstart3 = time.time()
bool_array = (rand_array < 0.5)
print(np.where(bool_array, rand_array, bool_array<0.5))
newnewfinish3 = time.time() - newnewstart3
print("Newnewtime3 in seconds (array scalars less than a value, then show only an array value under a less than condition): \n",newnewfinish3)

1000000
1e-06
[[ True False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
Time in seconds (compare an array == another array): 
 0.007191896438598633
tf.Tensor(
[[496.96500404 496.96500404 496.96500404 ... 496.96500404 496.96500404
  496.96500404]
 [508.49559857 508.49559857 508.49559857 ... 508.49559857 508.49559857
  508.49559857]
 [492.8734465  492.8734465  492.8734465  ... 492.8734465  492.8734465
  492.8734465 ]
 ...
 [516.31154455 516.31154455 516.31154455 ... 516.31154455 516.31154455
  516.31154455]
 [505.65816935 505.65816935 505.65816935 ... 505.65816935 505.65816935
  505.65816935]
 [501.07104011 501.07104011 501.07104011 ... 501.07104011 501.07104011
  501.07104011]], shape=(1000, 1000), dtype=float64)
Newtime in seconds (tf.einsum): 
 0.3255021572113037
0.500207
[[False  T

In [16]:
# https://www.geeksforgeeks.org/python-map-vs-for-loop/
# map() function is way faster computationally than a for loop

# union, intersection, difference between sets

In [34]:
import time
a={1,2,4,5,6}
b={5,6,4,9}

start = time.time()
print(a.union(b))
fin = time.time() - start
print("union", fin)
start = time.time()
print(a.intersection(b))
fin = time.time() - start
print("intersection a from b", fin)
start = time.time()
print(b.intersection(a))
fin = time.time() - start
print("intersection b from a", fin)
start = time.time()
print(a.difference(b))
fin = time.time() - start
print("difference of a from b", fin)
start = time.time()
print(b.difference(a))
fin = time.time() - start
print("difference of b from a", fin)

start = time.time()
c=(a^b)&b
print(c)
fin = time.time() - start
print("manual diff in b", fin)
start = time.time()
c=(a^b)&a
print(c)
fin = time.time() - start
print("manual diff in a", fin)

{1, 2, 4, 5, 6, 9}
union 0.00017547607421875
{4, 5, 6}
intersection a from b 0.00010180473327636719
{4, 5, 6}
intersection b from a 0.0001723766326904297
{1, 2}
difference of a from b 9.72747802734375e-05
{9}
difference of b from a 7.2479248046875e-05
{9}
manual diff in b 8.0108642578125e-05
{1, 2}
manual diff in a 7.653236389160156e-05


In [26]:
array1 = np.arange(0,1000,1)
array2 = np.arange(0,100,1)
print("Comparearray: \n", (array1 == array2))

Comparearray: 
 False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until
